solace.host=${SOLACE_HOST:tcp://localhost:55555}
solace.vpn=${SOLACE_VPN:default}
solace.username=${SOLACE_USERNAME:default}
solace.password=${SOLACE_PASSWORD:default}

solace.topic.orders-result=orders/result
solace.queue.orders-results=orders-results-q

spring.main.banner-mode=off
logging.level.root=WARN
