<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.newcron</groupId>
        <artifactId>global-dispatch</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>client-status</artifactId>
    <name>client-status</name>
    <description>Consola donde el cliente ve el estado (Accepted/Cancelled) de sus solicitudes</description>

    <dependencies>
        <dependency>
            <groupId>com.newcron</groupId>
            <artifactId>common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
    </dependencies>

    <build>
        <finalName>client-status</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>com.newcron.dispatch.clientstatus.ClientStatusApplication</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
